apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-labels-exporter.fullname" . }}
  labels:
    {{- include "node-labels-exporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
