apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-labels-exporter.fullname" . }}
  labels:
    {{- include "node-labels-exporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "node-labels-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "node-labels-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
