apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-labels-exporter.fullname" . }}
  labels:
    {{- include "node-labels-exporter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "node-labels-exporter.selectorLabels" . | nindent 4 }}
