image:
  pullPolicy: Always
  tag: test

args:
  - --zap-stacktrace-level=error
  - --zap-log-level=debug

webhooks:
  failurePolicy: Ignore
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values: ["default"]

metrics:
  enabled: true

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
