apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: default
  labels:
    app: alpine
spec:
  podManagementPolicy: Parallel # default is OrderedReady
  serviceName: test
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine
    spec:
      terminationGracePeriodSeconds: 3
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      nodeSelector:
        # node-role.kubernetes.io/control-plane: ""
        # kubernetes.io/hostname: kube-21
        # topology.kubernetes.io/zone: hvm-1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - alpine
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: alpine
          image: alpine
          command: ["sleep", "1d"]
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: alpine
