name: Release check

on:
  pull_request:
    branches:
      - main

jobs:
  build-publish:
    name: "Check release docs"
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    if: startsWith(github.head_ref, 'release-')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Release version
        if: startsWith(github.head_ref, 'release-please')
        run: jq -r '"TAG=v"+.[]' .github/release-please-manifest.json >> "$GITHUB_ENV"

      - name: Helm docs
        uses: gabe565/setup-helm-docs-action@v1
        with:
          version: v1.11.3

      - name: Generate
        run: make docs
      - name: Check
        run: git diff --exit-code
